repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace

  - repo: https://github.com/google/yamlfmt
    rev: 21ca5323a9c87ee37a434e0ca908efc0a89daa07 # frozen: v0.21.0
    hooks:
      - id: yamlfmt

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d # frozen: v0.11.0
    hooks:
      - id: shellcheck
        args: [-x]

  - repo: https://github.com/hadolint/hadolint
    rev: 57e1618d78fd469a92c1e584e8c9313024656623 # frozen: v2.14.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9 # frozen: v1.25.2
    hooks:
      - id: zizmor

  - repo: https://github.com/crate-ci/typos
    rev: v1.47.2
    hooks:
      - id: typos

  # Match old pre-commit prettier mirror that has been archived.
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        description: ''
        entry: prettier --write --ignore-unknown
        language: node
        types: [text]
        args: []
        require_serial: false
        additional_dependencies:
          # renovate: datasource=npm
          - prettier@3.8.4
        exclude: .github/workflows/.*.yml|.pre-commit-config.yaml|.github/renovate.json
