# syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM aclemons/slackware:current-full@sha256:d8250b8026ac95a08101f8ee92cc2e5ab5e2d558624a6bd0eef55c0a1d8adcd0

COPY scripts/install_slackrepo.sh /
RUN ./install_slackrepo.sh && rm /install_slackrepo.sh
RUN if [ "$(uname -m)" = "aarch64" ] ; then echo "export AARCH64=1" >> /etc/slackrepo/slackrepo_ponce.conf ; fi

CMD ["su", "-"]
