name: Slackware 15.0 Docker Images

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch ChangeLog
        run: |
          curl -s -f -o slackware-15.0/ChangeLog.txt.386 https://slackware.osuosl.org/slackware-15.0/ChangeLog.txt
          curl -s -f -o slackware-15.0/ChangeLog.txt.amd64 https://slackware.osuosl.org/slackware64-15.0/ChangeLog.txt

      - name: Cache Docker Builds
        id: cache-base-tarball
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.buildx-cache
            base_tarballs/
          key: ${{ runner.os }}-dockerbuild-15.0-${{ hashFiles('**/slackware-15.0/*', '**/scripts/*') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build prerequisites
        if: steps.cache-base-tarball.outputs.cache-hit != 'true'
        run: |
          docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined --rm -e RELEASENAME=slackware -e ARCH=i586 -e VERSION=15.0 -e CHOWN_TO="$(id -u):$(id -g)" -v "$(pwd):/data" -v "$(pwd)/scripts:/scripts" alpine:3.15 sh /scripts/build_base_image.sh
          docker run --cap-add SYS_ADMIN --security-opt apparmor:unconfined --rm -e RELEASENAME=slackware64 -e ARCH=x86_64 -e VERSION=15.0 -e CHOWN_TO="$(id -u):$(id -g)" -v "$(pwd):/data" -v "$(pwd)/scripts:/scripts" alpine:3.15 sh /scripts/build_base_image.sh
          cp *.tar base_tarballs/

      - name: Build prerequisites
        if: steps.cache-base-tarball.outputs.cache-hit == 'true'
        run: |
          cp base_tarballs/*tar .

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/slackware:15.0-base
          platforms: linux/amd64,linux/386,linux/arm/v7
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-next,mode=max
          context: .
          file: slackware-15.0/Dockerfile

      - name: Trim cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-next /tmp/.buildx-cache
